import type {CallspecDocument} from '../callspecDocument';
import {
    assertGeneratableSchema,
    sanitizeMethodName,
    schemaToTypes,
    typeNameForRoute,
} from './schemaToTypeScript';

const GENERATED_HEADER = `/**
 * Generated by callspec — do not edit manually.
 * Regenerate with: npx callspec <callspec.json> --output <file>
 */`;

export function generateClientSource(
    document: CallspecDocument,
    options?: {className?: string},
): string {

    const className = options?.className ?? 'ApiClient';
    const routeNames = Object.keys(document.routes).sort((a, b) => a.localeCompare(b));
    const typeBlocks: string[] = [];
    const methods: string[] = [];
    const usedMethodNames = new Set<string>();

    for (const routeName of routeNames) {

        const route = document.routes[routeName];

        assertGeneratableSchema(route.input, `Route "${routeName}" input`);
        assertGeneratableSchema(route.output, `Route "${routeName}" output`);

        const inputTypeName = typeNameForRoute(routeName, 'Input');
        const outputTypeName = typeNameForRoute(routeName, 'Output');
        const resultTypeName = typeNameForRoute(routeName, 'Result');
        const inputTypes = schemaToTypes(route.input, inputTypeName);
        const outputTypes = schemaToTypes(route.output, outputTypeName);
        let routeErrorTypeName: string | undefined;

        for (const generated of [...inputTypes.types, ...outputTypes.types]) {

            if (!typeBlocks.some((block) => block.includes(`export type ${generated.name}`))) {

                typeBlocks.push(generated.definition);

            }

        }

        if (route.errors) {

            const errorMembers: string[] = [];

            for (const [code, def] of Object.entries(route.errors).sort(([a], [b]) => a.localeCompare(b))) {

                if (def.data) {

                    assertGeneratableSchema(def.data, `Route "${routeName}" error "${code}" data`);
                    const dataTypeName = typeNameForRoute(routeName, `${code}Data`);
                    const dataTypes = schemaToTypes(def.data, dataTypeName);

                    for (const generated of dataTypes.types) {

                        if (!typeBlocks.some((block) => block.includes(`export type ${generated.name}`))) {

                            typeBlocks.push(generated.definition);

                        }

                    }

                    errorMembers.push(`{ error: ${JSON.stringify(code)}; data: ${dataTypeName} }`);

                } else {

                    errorMembers.push(`{ error: ${JSON.stringify(code)} }`);

                }

            }

            if (errorMembers.length) {

                routeErrorTypeName = typeNameForRoute(routeName, 'Error');

                typeBlocks.push(
                    `export type ${routeErrorTypeName} = ${errorMembers.join(' | ')};`,
                );

            }

        }

        typeBlocks.push(
            routeErrorTypeName
                ? `export type ${resultTypeName} = CallspecRouteResult<${outputTypeName}, ${routeErrorTypeName}>;`
                : `export type ${resultTypeName} = CallspecRouteResult<${outputTypeName}>;`,
        );

        let methodName = sanitizeMethodName(routeName);

        while (usedMethodNames.has(methodName)) {

            methodName = sanitizeMethodName(`${routeName}_${methodName}`);

        }

        usedMethodNames.add(methodName);

        methods.push(`
    async ${methodName}(input: ${inputTypeName}): Promise<${resultTypeName}> {
        return this.runtime.callResult<${outputTypeName}${routeErrorTypeName ? `, ${routeErrorTypeName}` : ''}>(${JSON.stringify(routeName)}, input);
    }`);

    }

    return [
        GENERATED_HEADER,
        '',
        `import {CallspecClient, type CallspecClientConfig, type CallspecRouteResult} from 'callspec/client';`,
        '',
        'export type ApiClientConfig = CallspecClientConfig;',
        '',
        ...typeBlocks,
        '',
        `export class ${className} {`,
        '    private readonly runtime: CallspecClient;',
        '',
        `    constructor(config: ApiClientConfig) {`,
        '        this.runtime = new CallspecClient(config);',
        '    }',
        ...methods,
        '}',
        '',
    ].join('\n');

}
