import type {CallspecDocument} from '../callspecDocument';
import {generateSchemasSection} from './generateSchemasSection';
import {
    assertGeneratableSchema,
    sanitizeMethodName,
    isEmptyObjectSchema,
    schemaToTypes,
    typeNameForRoute,
} from './schemaToTypeScript';

const GENERATED_HEADER = `/**
 * Generated by callspec — do not edit manually.
 * Regenerate with: npx callspec <mount-or-callspec.json> --output <file>
 */`;

function hasGeneratedTypeBlock(typeBlocks: string[], typeName: string): boolean {

    const typeHeader = `export type ${typeName}`;

    return typeBlocks.some(
        (block) => block.startsWith(`${typeHeader} `) || block.startsWith(`${typeHeader}=`),
    );

}

export function generateClientSource(
    document: CallspecDocument,
    options?: {className?: string},
): string {

    const className = options?.className ?? 'ApiClient';
    const routeNames = Object.keys(document.routes).sort((a, b) => a.localeCompare(b));
    const typeBlocks: string[] = [];
    const methods: string[] = [];
    const usedMethodNames = new Set<string>();
    const schemasSection = generateSchemasSection(document);

    for (const routeName of routeNames) {

        const route = document.routes[routeName];

        assertGeneratableSchema(route.input, `Route "${routeName}" input`);
        assertGeneratableSchema(route.output, `Route "${routeName}" output`);

        const inputTypeName = typeNameForRoute(routeName, 'Input');
        const outputTypeName = typeNameForRoute(routeName, 'Output');
        const resultTypeName = typeNameForRoute(routeName, 'Result');
        const inputTypes = schemaToTypes(route.input, inputTypeName);
        const outputTypes = schemaToTypes(route.output, outputTypeName);
        let routeErrorTypeName: string | undefined;

        for (const generated of [...inputTypes.types, ...outputTypes.types]) {

            if (!hasGeneratedTypeBlock(typeBlocks, generated.name)) {

                typeBlocks.push(generated.definition);

            }

        }

        if (route.errors) {

            const errorMembers: string[] = [];

            for (const [code, def] of Object.entries(route.errors).sort(([a], [b]) => a.localeCompare(b))) {

                if (def.data) {

                    assertGeneratableSchema(def.data, `Route "${routeName}" error "${code}" data`);
                    const dataTypeName = typeNameForRoute(routeName, `${code}Data`);
                    const dataTypes = schemaToTypes(def.data, dataTypeName);

                    for (const generated of dataTypes.types) {

                        if (!hasGeneratedTypeBlock(typeBlocks, generated.name)) {

                            typeBlocks.push(generated.definition);

                        }

                    }

                    const dataField = def.dataRequired === false
                        ? `data?: ${dataTypeName}`
                        : `data: ${dataTypeName}`;

                    errorMembers.push(`{ code: ${JSON.stringify(code)}; ${dataField} }`);

                } else {

                    errorMembers.push(`{ code: ${JSON.stringify(code)} }`);

                }

            }

            if (errorMembers.length) {

                routeErrorTypeName = typeNameForRoute(routeName, 'Error');

                typeBlocks.push(
                    `export type ${routeErrorTypeName} = ${errorMembers.join(' | ')};`,
                );

            }

        }

        typeBlocks.push(
            routeErrorTypeName
                ? `export type ${resultTypeName} = CallspecRouteResult<${outputTypeName}, ${routeErrorTypeName}>;`
                : `export type ${resultTypeName} = CallspecRouteResult<${outputTypeName}>;`,
        );

        let methodName = sanitizeMethodName(routeName);

        while (usedMethodNames.has(methodName)) {

            methodName = sanitizeMethodName(`${routeName}_${methodName}`);

        }

        usedMethodNames.add(methodName);

        const domainErrorCodes = route.errors
            ? Object.keys(route.errors).sort((a, b) => a.localeCompare(b))
            : undefined;

        const allowedErrorCodesJson = domainErrorCodes
            ? JSON.stringify(domainErrorCodes)
            : undefined;

        const domainErrorsJson = domainErrorCodes
            ? `{ ${domainErrorCodes.map((code) => {
                const def = route.errors![code]!;
                const parts: string[] = [];

                if (def.data) {

                    parts.push(`data: ${JSON.stringify(def.data)}`);
                    parts.push(`dataRequired: ${def.dataRequired === false ? 'false' : 'true'}`);

                } else {

                    parts.push('dataRequired: false');

                }

                return `${JSON.stringify(code)}: { ${parts.join(', ')} }`;
            }).join(', ')} }`
            : undefined;

        const callOptionParts: string[] = [];

        if (allowedErrorCodesJson) {

            callOptionParts.push(`allowedErrorCodes: ${allowedErrorCodesJson}`);

        }

        if (domainErrorsJson) {

            callOptionParts.push(`domainErrors: ${domainErrorsJson}`);

        }

        // Schema-guided ISO→Date revive (only at p.date() leaves).
        callOptionParts.push(`output: schemas.${sanitizeMethodName(routeName)}Output`);

        if (route.encoding === 'multipart') {

            callOptionParts.push(`encoding: 'multipart'`);

        }

        const callOptionsArg = `, { ${callOptionParts.join(', ')} }`;
        const inputArg = isEmptyObjectSchema(route.input)
            ? `input?: ${inputTypeName}`
            : `input: ${inputTypeName}`;

        methods.push(`
    async ${methodName}(${inputArg}): Promise<${resultTypeName}> {
        return this.runtime.callResult<${outputTypeName}${routeErrorTypeName ? `, ${routeErrorTypeName}` : ''}>(${JSON.stringify(routeName)}, input${callOptionsArg});
    }`);

    }

    const imports = [
        `import {CallspecClient, type CallspecClientConfig, type CallspecRouteResult} from 'callspec/client';`,
    ];

    if (schemasSection) {

        imports.push(`import {predicates as p, type Infer} from 'runtyp';`);

    }

    return [
        GENERATED_HEADER,
        '',
        ...imports,
        '',
        ...typeBlocks,
        '',
        `export class ${className} {`,
        '    private readonly runtime: CallspecClient;',
        '',
        `    constructor(config: CallspecClientConfig) {`,
        '        this.runtime = new CallspecClient(config);',
        '    }',
        ...methods,
        '}',
        ...(schemasSection ? ['', schemasSection, ''] : ['']),
    ].join('\n');

}
