import type {CallspecDocument} from '../callspecDocumentTypes';
import {
    assertGeneratableValidatorSchema,
    schemaToRuntyp,
    typeNameForExport,
} from './schemaToRuntyp';
import {sanitizeMethodName, typeNameForRoute} from '../generateClient/schemaToTypeScript';

const GENERATED_HEADER = `/**
 * Generated by callspec — do not edit manually.
 * Regenerate with: npx callspec <mount-or-callspec.json> --output <file> --validators
 */`;

function claimPredName(usedNames: Set<string>, name: string, label: string): string {

    if (usedNames.has(name)) {

        throw new Error(`Duplicate validator name "${name}" (${label})`);

    }

    usedNames.add(name);

    return name;

}

export function generateValidatorsSource(document: CallspecDocument): string {

    const blocks: string[] = [];
    const usedPredNames = new Set<string>();
    const exportNames = document.exports
        ? Object.keys(document.exports).sort((a, b) => a.localeCompare(b))
        : [];
    const routeNames = Object.keys(document.routes).sort((a, b) => a.localeCompare(b));

    for (const exportKey of exportNames) {

        const schema = document.exports![exportKey];

        assertGeneratableValidatorSchema(schema, `Export "${exportKey}"`);

        const predName = claimPredName(
            usedPredNames,
            sanitizeMethodName(exportKey),
            `export "${exportKey}"`,
        );
        const typeName = typeNameForExport(exportKey);
        const expr = schemaToRuntyp(schema);

        blocks.push(`export const ${predName} = ${expr};`);
        blocks.push(`export type ${typeName} = Infer<typeof ${predName}>;`);
        blocks.push('');

    }

    for (const routeName of routeNames) {

        const route = document.routes[routeName];

        assertGeneratableValidatorSchema(route.input, `Route "${routeName}" input`);
        assertGeneratableValidatorSchema(route.output, `Route "${routeName}" output`);

        const inputPred = claimPredName(
            usedPredNames,
            `${sanitizeMethodName(routeName)}Input`,
            `route "${routeName}" input`,
        );
        const outputPred = claimPredName(
            usedPredNames,
            `${sanitizeMethodName(routeName)}Output`,
            `route "${routeName}" output`,
        );
        const inputType = typeNameForRoute(routeName, 'Input');
        const outputType = typeNameForRoute(routeName, 'Output');

        blocks.push(`export const ${inputPred} = ${schemaToRuntyp(route.input)};`);
        blocks.push(`export type ${inputType} = Infer<typeof ${inputPred}>;`);
        blocks.push('');
        blocks.push(`export const ${outputPred} = ${schemaToRuntyp(route.output)};`);
        blocks.push(`export type ${outputType} = Infer<typeof ${outputPred}>;`);
        blocks.push('');

    }

    return [
        GENERATED_HEADER,
        '',
        `import {predicates as p, type Infer} from 'runtyp';`,
        '',
        ...blocks,
    ].join('\n');

}
